export enum CodigoStatus {
    CONTINO = 100,
    TROCANDO_PROTOCOLOS = 101,
    PROCESSANDO = 102,
    DICAS_PRELIMINARES = 103,
    OK = 200,
    CRIADO = 201,
    ACEITO = 202,
    INFORMACAO_NAO_AUTORITATIVA = 203,
    SEM_CONTEUDO = 204,
    RESETAR_CONTEUDO = 205,
    CONTEUDO_PARCIAL = 206,
    MULTI_STATUS = 207,
    JA_REPORTADO = 208,
    IM_USADO = 226,
    MULTIPLAS_ESCOLHAS = 300,
    MOVIDO_PERMANENTEMENTE = 301,
    ENCONTRADO = 302,
    VER_OUTRO = 303,
    NAO_MODIFICADO = 304,
    USAR_PROXY = 305,
    REDIRECIONAMENTO_TEMPORARIO = 307,
    REDIRECIONAMENTO_PERMANENTE = 308,
    REQUISICAO_MAL_FORMATADA = 400,
    NAO_AUTENTICADO = 401,
    PAGAMENTO_REQUERIDO = 402,
    PROIBIDO = 403,
    NAO_ENCONTRADO = 404,
    METODO_NAO_PERMITIDO = 405,
    NAO_ACEITAVEL = 406,
    AUTENTICACAO_PROXY_REQUERIDA = 407,
    TEMPO_ESGOTADO = 408,
    CONFLITO = 409,
    REMOVIDO = 410,
    TAMANHO_REQUERIDO = 411,
    PRE_CONDICAO_FALHOU = 412,
    CORPO_TAMANHO_EXCESSIVO = 413,
    URI_TAMANHO_EXCESSIVO = 414,
    TIPO_MIDIA_NAO_SUPORTADO = 415,
    RANGE_NAO_SATISFEITRO = 416,
    EXPECTATIVA_FALHOU = 417,
    SOU_UMA_PANEQUECA = 418,
    REQUISICAO_MAL_DIRECIONADA = 421,
    ENTIDADE_INPROCESSAVEL = 422,
    BLOQUEADO = 423,
    DEPENDENCIA_FALHOU = 424,
    MUITO_CEDO = 425,
    ATUALIZACAO_REQUERIDA = 426,
    PRE_CONDICAO_REQUERIDA = 428,
    MUITAS_REQUISICOES = 429,
    CABECALHOS_REQUISICAO_TAMANHO_EXCESSIVO = 431,
    INDISPONIVEL_POR_MOTIVOS_LEGAIS = 450,
    ERRO_INTERNO_SERVIDOR = 500,
    NAO_IMPLEMENTADO = 501,
    GATEWAY_INCORRETO = 502,
    SERVICO_INDISPONIVEL = 503,
    TEMPO_GATEWAY_ESGOTADO = 504,
    VERSAO_HTTP_NAO_SUPORTADA = 505,
    VARIANTE_TAMBEM_NEGOCIA = 506,
    ARMAZENAMENTO_INSUFICIENTE = 507,
    LOOP_DETECTADO = 508,
    NAO_EXTENDIDO = 510,
    AUTENTICACAO_REDE_REQUERIDA = 511,
}

export const DescricaoCodigoStatus: Record<CodigoStatus, string> = {
    [CodigoStatus.CONTINO]: "O servidor recebeu os cabeçalhos da requisição e o cliente deve prosseguir para enviar o corpo.",
    [CodigoStatus.TROCANDO_PROTOCOLOS]: "O servidor está trocando protocolos conforme solicitado pelo cliente.",
    [CodigoStatus.PROCESSANDO]: "O servidor está processando a requisição, mas ainda não há resposta final.",
    [CodigoStatus.DICAS_PRELIMINARES]: "O servidor está retornando dicas sobre a resposta antes da resposta final estar pronta.",
    [CodigoStatus.OK]: "A requisição foi bem sucedida.",
    [CodigoStatus.CRIADO]: "A requisição foi atendida e um novo recurso foi criado.",
    [CodigoStatus.ACEITO]: "A requisição foi aceita para processamento, mas ainda não foi completada.",
    [CodigoStatus.INFORMACAO_NAO_AUTORITATIVA]: "A requisição foi bem sucedida, mas a informação retornada é de uma cópia em cache.",
    [CodigoStatus.SEM_CONTEUDO]: "A requisição foi bem sucedida, mas não há conteúdo para retornar.",
    [CodigoStatus.RESETAR_CONTEUDO]: "A requisição foi bem sucedida e o cliente deve redefinir a visualização do documento.",
    [CodigoStatus.CONTEUDO_PARCIAL]: "O servidor atendeu a requisição GET parcial para o recurso.",
    [CodigoStatus.MULTI_STATUS]: "O servidor atendeu uma resposta Multi-Status com múltiplos códigos de status.",
    [CodigoStatus.JA_REPORTADO]: "O servidor já atendeu a requisição e a resposta é redundante.",
    [CodigoStatus.IM_USADO]: "O servidor atendeu a requisição e o recurso já foi reportado.",
    [CodigoStatus.MULTIPLAS_ESCOLHAS]: "O recurso solicitado tem múltiplas representações e o cliente pode escolher uma.",
    [CodigoStatus.MOVIDO_PERMANENTEMENTE]: "O recurso solicitado foi movido permanentemente para uma nova URL.",
    [CodigoStatus.ENCONTRADO]: "O recurso solicitado foi movido temporariamente para uma URL diferente.",
    [CodigoStatus.VER_OUTRO]: "O recurso solicitado pode ser encontrado em uma URL diferente e deve ser acessado via GET.",
    [CodigoStatus.NAO_MODIFICADO]: "O recurso solicitado não foi modificado desde a última requisição.",
    [CodigoStatus.USAR_PROXY]: "O recurso solicitado deve ser acessado através do proxy especificado.",
    [CodigoStatus.REDIRECIONAMENTO_TEMPORARIO]: "O recurso solicitado foi movido temporariamente para uma URL diferente.",
    [CodigoStatus.REDIRECIONAMENTO_PERMANENTE]: "O recurso solicitado foi movido permanentemente para uma nova URL.",
    [CodigoStatus.REQUISICAO_MAL_FORMATADA]: "O servidor não consegue processar a requisição devido a sintaxe inválida ou requisição malformada.",
    [CodigoStatus.NAO_AUTENTICADO]: "A requisição requer autenticação ou as credenciais são inválidas.",
    [CodigoStatus.PAGAMENTO_REQUERIDO]: "A requisição requer pagamento ou o pagamento falhou.",
    [CodigoStatus.PROIBIDO]: "O servidor entendeu a requisição, mas recusa autorizá-la.",
    [CodigoStatus.NAO_ENCONTRADO]: "O recurso solicitado não pôde ser encontrado no servidor.",
    [CodigoStatus.METODO_NAO_PERMITIDO]: "O método especificado na requisição não é permitido para o recurso.",
    [CodigoStatus.NAO_ACEITAVEL]: "O servidor não consegue produzir uma resposta que corresponda aos cabeçalhos Accept do cliente.",
    [CodigoStatus.AUTENTICACAO_PROXY_REQUERIDA]: "O servidor proxy requer autenticação para atender a requisição.",
    [CodigoStatus.TEMPO_ESGOTADO]: "O servidor expirou o tempo de espera pela requisição do cliente.",
    [CodigoStatus.CONFLITO]: "A requisição entra em conflito com o estado atual do servidor.",
    [CodigoStatus.REMOVIDO]: "O recurso solicitado não está mais disponível e não estará disponível novamente.",
    [CodigoStatus.TAMANHO_REQUERIDO]: "O servidor requer o cabeçalho Content-Length na requisição.",
    [CodigoStatus.PRE_CONDICAO_FALHOU]: "Uma pré-condição nos cabeçalhos da requissão foi avaliada como falsa.",
    [CodigoStatus.CORPO_TAMANHO_EXCESSIVO]: "O corpo da requisição é maior do que o servidor está disposto ou capaz de processar.",
    [CodigoStatus.URI_TAMANHO_EXCESSIVO]: "A URI da requisição é maior do que o servidor pode interpretar.",
    [CodigoStatus.TIPO_MIDIA_NAO_SUPORTADO]: "O servidor não suporta o tipo de mídia na requisição.",
    [CodigoStatus.RANGE_NAO_SATISFEITRO]: "O intervalo especificado na requisição não pode ser atendido.",
    [CodigoStatus.EXPECTATIVA_FALHOU]: "O servidor não consegue atender aos requisitos indicados no cabeçalho Expect.",
    [CodigoStatus.SOU_UMA_PANEQUECA]: "O servidor recusa fazer café porque é uma paneca.",
    [CodigoStatus.REQUISICAO_MAL_DIRECIONADA]: "A requisição foi direcionada a um servidor que não consegue produzir uma resposta.",
    [CodigoStatus.ENTIDADE_INPROCESSAVEL]: "O servidor entende a entidade, mas não consegue processar as instruções contidas.",
    [CodigoStatus.BLOQUEADO]: "O recurso solicitado está bloqueado e não pode ser modificado.",
    [CodigoStatus.DEPENDENCIA_FALHOU]: "A requisição falhou devido a uma dependência de outra requisição que falhou.",
    [CodigoStatus.MUITO_CEDO]: "O servidor não está disposto a processar uma requisição muito cedo.",
    [CodigoStatus.ATUALIZACAO_REQUERIDA]: "O servidor requer que o cliente atualize para um protocolo diferente.",
    [CodigoStatus.PRE_CONDICAO_REQUERIDA]: "O servidor requer que a requisição inclua um cabeçalho de pré-condição.",
    [CodigoStatus.MUITAS_REQUISICOES]: "O usuário enviou muitas requisições em um determinado período de tempo.",
    [CodigoStatus.CABECALHOS_REQUISICAO_TAMANHO_EXCESSIVO]: "O servidor não está disposto a processar a requisição devido a campos de cabeçalho muito grandes.",
    [CodigoStatus.INDISPONIVEL_POR_MOTIVOS_LEGAIS]: "O servidor está indisponível por motivos legais.",
    [CodigoStatus.ERRO_INTERNO_SERVIDOR]: "O servidor encontró uma condição inesperada que impediu o atendimento da requisição.",
    [CodigoStatus.NAO_IMPLEMENTADO]: "O servidor não suporta a funcionalidade necessária para atender a requisição.",
    [CodigoStatus.GATEWAY_INCORRETO]: "O servidor recebeu uma resposta inválida de um servidor upstream.",
    [CodigoStatus.SERVICO_INDISPONIVEL]: "O servidor está atualmente indisponível devido a sobrecarga ou manutenção.",
    [CodigoStatus.TEMPO_GATEWAY_ESGOTADO]: "O servidor não recebeu uma resposta oportuna de um servidor upstream.",
    [CodigoStatus.VERSAO_HTTP_NAO_SUPORTADA]: "O servidor não suporta a versão do protocolo HTTP usada na requisição.",
    [CodigoStatus.VARIANTE_TAMBEM_NEGOCIA]: "O servidor tem um erro de negociação interno e não pode prosseguir.",
    [CodigoStatus.ARMAZENAMENTO_INSUFICIENTE]: "O servidor tem armazenamento insuficiente para completar a requisição.",
    [CodigoStatus.LOOP_DETECTADO]: "O servidor detectou um loop infinito ao processar a requisição.",
    [CodigoStatus.NAO_EXTENDIDO]: "São necessárias mais extensões para atender a requisição.",
    [CodigoStatus.AUTENTICACAO_REDE_REQUERIDA]: "O cliente precisa autenticar para obter acesso à rede.",
};
