export enum StatusCode {
    CONTINUE = 100,
    SWITCHING_PROTOCOLS = 101,
    PROCESSING = 102,
    EARLY_HINTS = 103,
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NON_AUTHORITATIVE_INFORMATION = 203,
    NO_CONTENT = 204,
    RESET_CONTENT = 205,
    PARTIAL_CONTENT = 206,
    MULTI_STATUS = 207,
    ALREADY_REPORTED = 208,
    IM_USED = 226,
    MULTIPLE_CHOICES = 300,
    MOVED_PERMANENTLY = 301,
    FOUND = 302,
    SEE_OTHER = 303,
    NOT_MODIFIED = 304,
    USE_PROXY = 305,
    TEMPORARY_REDIRECT = 307,
    PERMANENT_REDIRECT = 308,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    PAYMENT_REQUIRED = 402,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    METHOD_NOT_ALLOWED = 405,
    NOT_ACCEPTABLE = 406,
    PROXY_AUTHENTICATION_REQUIRED = 407,
    REQUEST_TIMEOUT = 408,
    CONFLICT = 409,
    GONE = 410,
    LENGTH_REQUIRED = 411,
    PRECONDITION_FAILED = 412,
    PAYLOAD_TOO_LARGE = 413,
    URI_TOO_LONG = 414,
    UNSUPPORTED_MEDIA_TYPE = 415,
    RANGE_NOT_SATISFIABLE = 416,
    EXPECTATION_FAILED = 417,
    IM_A_TEAPOT = 418,
    MISDIRECTED_REQUEST = 421,
    UNPROCESSABLE_ENTITY = 422,
    LOCKED = 423,
    FAILED_DEPENDENCY = 424,
    TOO_EARLY = 425,
    UPGRADE_REQUIRED = 426,
    PRECONDITION_REQUIRED = 428,
    TOO_MANY_REQUESTS = 429,
    REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
    UNAVAILABLE_FOR_LEGAL_REASONS = 451,
    INTERNAL_SERVER_ERROR = 500,
    NOT_IMPLEMENTED = 501,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
    GATEWAY_TIMEOUT = 504,
    HTTP_VERSION_NOT_SUPPORTED = 505,
    VARIANT_ALSO_NEGOTIATES = 506,
    INSUFFICIENT_STORAGE = 507,
    LOOP_DETECTED = 508,
    NOT_EXTENDED = 510,
    NETWORK_AUTHENTICATION_REQUIRED = 511,
}

export const StatusCodeDescription: Record<StatusCode, string> = {
    [StatusCode.CONTINUE]: "The server has received the request headers and the client should proceed to send the body.",
    [StatusCode.SWITCHING_PROTOCOLS]: "The server is switching protocols as requested by the client.",
    [StatusCode.PROCESSING]: "The server is processing the request but there is no final response yet.",
    [StatusCode.EARLY_HINTS]: "The server is returning hints about the response before the final response is ready.",
    [StatusCode.OK]: "The request has succeeded.",
    [StatusCode.CREATED]: "The request has been fulfilled and a new resource has been created.",
    [StatusCode.ACCEPTED]: "The request has been accepted for processing but has not been completed.",
    [StatusCode.NON_AUTHORITATIVE_INFORMATION]: "The request has succeeded but the returned information is from a cached copy.",
    [StatusCode.NO_CONTENT]: "The request has succeeded but there is no content to return.",
    [StatusCode.RESET_CONTENT]: "The request has succeeded and the client should reset the document view.",
    [StatusCode.PARTIAL_CONTENT]: "The server has fulfilled the partial GET request for the resource.",
    [StatusCode.MULTI_STATUS]: "The server has fulfilled a Multi-Status response with multiple status codes.",
    [StatusCode.ALREADY_REPORTED]: "The server has already fulfilled the request and the response is redundant.",
    [StatusCode.IM_USED]: "The server has fulfilled the request and the resource has already been reported.",
    [StatusCode.MULTIPLE_CHOICES]: "The requested resource has multiple representations and the client can choose one.",
    [StatusCode.MOVED_PERMANENTLY]: "The requested resource has been permanently moved to a new URL.",
    [StatusCode.FOUND]: "The requested resource has been temporarily moved to a different URL.",
    [StatusCode.SEE_OTHER]: "The requested resource can be found at a different URL and should be accessed via GET.",
    [StatusCode.NOT_MODIFIED]: "The requested resource has not been modified since the last request.",
    [StatusCode.USE_PROXY]: "The requested resource must be accessed through the specified proxy.",
    [StatusCode.TEMPORARY_REDIRECT]: "The requested resource has been temporarily moved to a different URL.",
    [StatusCode.PERMANENT_REDIRECT]: "The requested resource has been permanently moved to a new URL.",
    [StatusCode.BAD_REQUEST]: "The server cannot process the request due to invalid syntax or malformed request.",
    [StatusCode.UNAUTHORIZED]: "The request requires authentication or the credentials are invalid.",
    [StatusCode.PAYMENT_REQUIRED]: "The request requires payment or the payment has failed.",
    [StatusCode.FORBIDDEN]: "The server understood the request but refuses to authorize it.",
    [StatusCode.NOT_FOUND]: "The requested resource could not be found on the server.",
    [StatusCode.METHOD_NOT_ALLOWED]: "The method specified in the request is not allowed for the resource.",
    [StatusCode.NOT_ACCEPTABLE]: "The server cannot produce a response matching the client's Accept headers.",
    [StatusCode.PROXY_AUTHENTICATION_REQUIRED]: "The proxy server requires authentication to fulfill the request.",
    [StatusCode.REQUEST_TIMEOUT]: "The server timed out waiting for the request from the client.",
    [StatusCode.CONFLICT]: "The request conflicts with the current state of the server.",
    [StatusCode.GONE]: "The requested resource is no longer available and will not be available again.",
    [StatusCode.LENGTH_REQUIRED]: "The server requires the Content-Length header in the request.",
    [StatusCode.PRECONDITION_FAILED]: "A precondition in the request headers evaluated to false.",
    [StatusCode.PAYLOAD_TOO_LARGE]: "The request body is larger than the server is willing or able to process.",
    [StatusCode.URI_TOO_LONG]: "The request URI is longer than the server can interpret.",
    [StatusCode.UNSUPPORTED_MEDIA_TYPE]: "The server does not support the media type in the request.",
    [StatusCode.RANGE_NOT_SATISFIABLE]: "The range specified in the request cannot be fulfilled.",
    [StatusCode.EXPECTATION_FAILED]: "The server cannot meet the requirements indicated in the Expect header.",
    [StatusCode.IM_A_TEAPOT]: "The server refuses to brew coffee because it is a teapot.",
    [StatusCode.MISDIRECTED_REQUEST]: "The request was directed to a server that is not able to produce a response.",
    [StatusCode.UNPROCESSABLE_ENTITY]: "The server understands the entity but cannot process the contained instructions.",
    [StatusCode.LOCKED]: "The requested resource is locked and cannot be modified.",
    [StatusCode.FAILED_DEPENDENCY]: "The request failed due to a dependency on another request that failed.",
    [StatusCode.TOO_EARLY]: "The server is unwilling to process a request that is too early.",
    [StatusCode.UPGRADE_REQUIRED]: "The server requires the client to upgrade to a different protocol.",
    [StatusCode.PRECONDITION_REQUIRED]: "The server requires the request to include a Precondition header.",
    [StatusCode.TOO_MANY_REQUESTS]: "The user has sent too many requests in a given amount of time.",
    [StatusCode.REQUEST_HEADER_FIELDS_TOO_LARGE]: "The server is unwilling to process the request due to large header fields.",
    [StatusCode.UNAVAILABLE_FOR_LEGAL_REASONS]: "The server is unavailable due to legal reasons.",
    [StatusCode.INTERNAL_SERVER_ERROR]: "The server encountered an unexpected condition that prevented it from fulfilling the request.",
    [StatusCode.NOT_IMPLEMENTED]: "The server does not support the functionality required to fulfill the request.",
    [StatusCode.BAD_GATEWAY]: "The server received an invalid response from an upstream server.",
    [StatusCode.SERVICE_UNAVAILABLE]: "The server is currently unavailable due to overload or maintenance.",
    [StatusCode.GATEWAY_TIMEOUT]: "The server did not receive a timely response from an upstream server.",
    [StatusCode.HTTP_VERSION_NOT_SUPPORTED]: "The server does not support the HTTP protocol version used in the request.",
    [StatusCode.VARIANT_ALSO_NEGOTIATES]: "The server has an internal negotiation error and cannot proceed.",
    [StatusCode.INSUFFICIENT_STORAGE]: "The server has insufficient storage to complete the request.",
    [StatusCode.LOOP_DETECTED]: "The server detected an infinite loop while processing the request.",
    [StatusCode.NOT_EXTENDED]: "Further extensions are needed to fulfill the request.",
    [StatusCode.NETWORK_AUTHENTICATION_REQUIRED]: "The client needs to authenticate to gain network access.",
};